language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sysbender/docker-react -f Dockerfile.dev .
  - docker run  sysbender/docker-react npm run test -- --coverage


